import { PrismaClient } from '@prisma/client'; import bcrypt from 'bcryptjs';
const db = new PrismaClient();
const adminEmail = process.env.ADMIN_EMAIL || '010421aziz@gmail.com';
const adminPassword = process.env.ADMIN_PASSWORD || 'Azio2104';
async function main() { const password = await bcrypt.hash(adminPassword, 12); await db.admin.upsert({ where:{email:adminEmail}, update:{password}, create:{email:adminEmail,password,name:'Quran Academy'} });
 await db.contact.upsert({where:{id:'academy-contact'},update:{},create:{id:'academy-contact',address:'Бишкек шаары, Кызыл-Адыр 156',phone:'+996 501 041 617',instagram:'https://www.instagram.com/quranacademy.kg'}});
 const formConfig = await db.formConfig.findUnique({ where: { id: 'main' } });
 if (!formConfig) await db.formConfig.create({ data: { id: 'main', fields: { create: [
  { label: 'Аты-жөнүңүз', name: 'name', type: 'text', required: true, order: 0 },
  { label: 'Телефон номериңиз', name: 'phone', type: 'phone', required: true, order: 1 },
  { label: 'Email (милдеттүү эмес)', name: 'email', type: 'email', required: false, order: 2 },
  { label: 'Сурооңуз', name: 'message', type: 'textarea', required: true, order: 3 },
 ] } } });
 await db.siteSettings.upsert({where:{id:'main'},update:{},create:{id:'main',heroLocation:'БИШКЕК · КЫРГЫЗСТАН',heroTitle:'Куран Академия',heroSubtitle:'Куран жаттоо жана ижаза алуу медресеси',heroDescription:'Куранды туура окууну, жаттоону жана ижаза алуу жолун үйрөтүүчү заманбап медресе.',aboutTitle:'Курандын нуру менен тарбияланган муун',aboutText:'Куран Академия — Куран жаттоо жана ижаза берүү багытындагы медресе.\nМаксатыбыз — Куранды туура окуган, жаттаган, адеп-ахлакка тарбияланган жана пайдалуу илимге ээ болгон муунду тарбиялоо.',featuresTitle:'Илим, адеп жана ишеним бир жерде',programsTitle:'Ар бир кадам үчүн так программа',teachersTitle:'Илимди аманат катары жеткирген устаздар',galleryTitle:'Галерея',contactTitle:'Сизди Академияда күтөбүз',logo:'',aboutImage:'',stats:[{value:'500+',label:'Окуучу'},{value:'10+',label:'Устаз'},{value:'5',label:'Программа'},{value:'100%',label:'Берилгендик'}]}});
 await db.siteSettings.update({where:{id:'main'},data:{heroSubtitle:'Куранды туура окууга, жаттоого жана ижаза алууга жол ачкан билим ордосу.',heroDescription:'Сапаттуу билим, жеке көзөмөл жана бекем тарбия аркылуу окуучунун Куран менен байланышын күчөтөбүз.',aboutTitle:'Курандын нуру менен тарбияланган муун',aboutText:'Куран Академия — Куран жаттоо, тажвид жана ижаза багытында системалуу билим берген медресе.\nБиз ар бир окуучуга түшүнүктүү программа, тажрыйбалуу устаз жана жылуу чөйрө сунуштайбыз.',featuresTitle:'Илим, адеп жана ишеним бир жерде',programsTitle:'Максатыңызга ылайык түзүлгөн окуу багыттары',teachersTitle:'Билимин аманат катары жеткирген устаздар',galleryTitle:'Академиянын жашоосунан көз ирмемдер',contactTitle:'Билим жолун бүгүн баштаңыз.'}});
 const programs: [string,string,string,string[]][]=[['Куран жаттоо','Толук Куран жаттоо программасы.','BookOpen',['Толук жаттоо','Кайталоо','Тажвид']],['Ижаза','Куранды санад менен окуу.','ScrollText',['Санад','Кыраат','Устаздык көзөмөл']],['Араб тили','Куран тилин түшүнүүгө багытталган терең курс.','Languages',['Нахв','Сарф','Окуу','Жазуу','Сүйлөө']],['Англис тили','Заманбап англис тилинин практикалык программасы.','MessageCircle',['Grammar','Speaking','Reading','Listening']],['Диний сабактар','Негизги ислам илимдери.','Landmark',['Фикх','Акыда','Хадис','Сира','Тафсир']]];
 for (const [index, row] of programs.entries()) { const [title,description,icon,topics]=row; await db.program.upsert({where:{id:`program-${index}`},update:{},create:{id:`program-${index}`,title,description,icon,topics,order:index}}); }
 await db.program.update({where:{id:'program-0'},data:{title:'Куран жаттоо',description:'Куранды туура окуу, жаттоо жана бекем кайталоо үчүн комплекстүү программа.',topics:['Жаттоо','Кайталоо','Тажвид']}});
 await db.program.update({where:{id:'program-1'},data:{title:'Ижаза',description:'Санад менен окууну өркүндөтүп, ижаза алууга системалуу даярдык.',topics:['Санад','Кыраат','Жеке көзөмөл']}});
 await db.program.update({where:{id:'program-2'},data:{title:'Араб тили',description:'Курандын тилин түшүнүү үчүн грамматика, сөз байлыгы жана сүйлөө көндүмдөрү.',topics:['Нахв','Сарф','Окуу','Сүйлөө']}});
 await db.program.update({where:{id:'program-3'},data:{title:'Англис тили',description:'Окуу, сүйлөө жана күнүмдүк баарлашуу үчүн практикалык тил программасы.',topics:['Grammar','Speaking','Reading','Listening']}});
 await db.program.update({where:{id:'program-4'},data:{title:'Диний сабактар',description:'Фикх, акыйда, хадис, сира жана тафсир боюнча системалуу негизги билим.',topics:['Фикх','Акыйда','Хадис','Сира','Тафсир']}}); }
main().finally(()=>db.$disconnect());
